---

- include: multi_os.yml
  tags:
    - config_nagios_plugins
    - test_nagios_plugins

- name: Install checkmk dependencies
  apt:
    name: "{{ checkmk_deps }}"
    state: present

- name: Ensure download directory is present
  file: path={{ download_dir }} state=directory

- include: build-check-mk-livestatus.yml

- name: lineinfile - configure nagios.cfg for check-mk
  lineinfile: "dest={{ nagios_config_file }} regexp='{{ item.src }}' line='{{ item.value }}'"
  with_items:
  - { src: "^broker_module=", value: "broker_module={{ nagios_config_broker_module }}" }
  notify: 
    - systemctl daemon-reload
    - Restart Nagios

- name: ensure handlers runs before continue
  meta: flush_handlers

- name: wait for nagios socket to start
  wait_for:
    path: "{{ nagios_live_sock }}"
